### ISSUE TITLE
Phishtank related error...

### ISSUE THREAD

**Issue by faysalam** [CIRCL/url-abuse#7]
Hello again,

Thanks for the help on the previous issue. 
now the service is started with no issues and the web interface is running as expected, but when I submit a URL I get this issue:

```
2017-05-04 02:47:41,111] ERROR in app: Exception on /phishtank [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [04/May/2017 02:47:41] "POST /phishtank HTTP/1.1" 500 -
[2017-05-04 02:47:41,113] ERROR in app: Exception on /virustotal_report [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
[2017-05-04 02:47:41,115] ERROR in app: Exception on /googlesafebrowsing [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [04/May/2017 02:47:41] "POST /virustotal_report HTTP/1.1" 500 -
127.0.0.1 - - [04/May/2017 02:47:41] "POST /googlesafebrowsing HTTP/1.1" 500 -
```

....
the error actually continues for /urlquery, /ticket, /whois, /resolve, /eupi, /pdnscircl, and /psslcircl

Could you please help?

**Comment by faysalam** [comment]
please note that multiple instances of "worker.py" are running and that Redis-server is also started.
